"""
Convert .vbn model to C header for ESP32 flash embedding.

Usage:
    python scripts/vbn_to_header.py
    python scripts/vbn_to_header.py checkpoints/vedu_model.vbn inference/esp32/vedu_esp32/vedu_model_data.h
"""

import os
import sys


def vbn_to_header(vbn_path, header_path):
    with open(vbn_path, 'rb') as f:
        data = f.read()

    total_bytes = len(data)
    print(f"Model size: {total_bytes:,} bytes ({total_bytes / 1024:.1f} KB)")

    with open(header_path, 'w') as h:
        h.write("// AUTO-GENERATED by vbn_to_header.py\n")
        h.write("// Do not edit manually.\n")
        h.write(f"// Source: {os.path.basename(vbn_path)}\n")
        h.write(f"// Size: {total_bytes:,} bytes\n\n")
        h.write("#pragma once\n")
        h.write("#include <cstdint>\n\n")

        h.write("#ifdef ESP32\n")
        h.write("  #include <pgmspace.h>\n")
        h.write("  #define MODEL_STORAGE PROGMEM\n")
        h.write("#else\n")
        h.write("  #define MODEL_STORAGE\n")
        h.write("#endif\n\n")

        h.write(f"static const uint32_t VEDU_MODEL_SIZE = {total_bytes};\n\n")
        h.write("static const uint8_t VEDU_MODEL_DATA[] MODEL_STORAGE = {\n")

        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
            h.write(f"    {hex_vals},\n")

        h.write("};\n")

    print(f"Header written: {header_path}")
    print(f"Flash footprint: {total_bytes:,} bytes")


if __name__ == "__main__":
    vbn_path = sys.argv[1] if len(sys.argv) > 1 else "checkpoints/vedu_model.vbn"
    header_path = sys.argv[2] if len(sys.argv) > 2 else "inference/esp32/vedu_esp32/vedu_model_data.h"
    vbn_to_header(vbn_path, header_path)
